Add media query
digia3d/First-Portfolio pull request #4
Opened 2022-06-02 19:52 UTC by digia3d

Add Media Query for section headlines works and contact, and fix errors in html.

2022-06-02 22:10 UTC, tresorsawasawa requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @digia3d 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![almost-there](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 

## Rewquired changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me [@tresorsawasawa](https://github.com/tresorsawasawa) when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-02 22:10 UTC, tresorsawasawa commented on index.html
> +        </li>
- [x] I think it would be better if you correct this typo error to make the project more professional. You wrote `Portoflio` instead of `Portfolio`.

2022-06-02 22:10 UTC, tresorsawasawa commented on index.html
>        </div>
- [ **OPTIONAL** ] I think I think it would be to rename the logo's name to not make confusion for users. The portfolio belongs to `Aleksandra Ujvari` and not to `John Doe`. I suggest you use one of your names as the `logo`.

2022-06-02 22:10 UTC, tresorsawasawa commented on style.css
> +}
- [ **OPTIONAL** ] I think it would be better :100: :+1:  if you wrap all the `desktop's styling` in one `@media query` for best practices, not repeat yourself every time and this will make your code cleaner. I know you can do it :muscle: :muscle: i.e. 
```bash
@media only screen and (min-width: 768px) {

    all your code to style the desk top version here

  }
```

2022-06-02 22:10 UTC, tresorsawasawa commented on style.css
> +}
- [x] Kindly make sure to add the correct spacing between **languages items**, **Frameworks items**, and **Skills items** to make the page clear and match the Figma template. Also, make sure to add the missing `horizontal` line at the top.
### Figma design 
![f_list](https://user-images.githubusercontent.com/83042742/171738238-85d30cdb-29a6-4cda-94ce-909243f9d7c0.png)

###  Your design 
![s_list](https://user-images.githubusercontent.com/83042742/171738356-36dd03df-aad7-442f-bfca-5b53383614d3.png)

2022-06-02 22:10 UTC, tresorsawasawa commented on style.css
> +  }
- [x] Kindly make sure to adjust the **moon image** at the background to the right position. When trying to change the screen width it covers some text to not be clear.
### Figma design
![f_bg](https://user-images.githubusercontent.com/83042742/171739929-ae082867-0871-4dba-8a04-038ffd879fba.png)
### Your Design
![s_bg](https://user-images.githubusercontent.com/83042742/171740001-b6bab175-eb34-419c-931e-657ce6d16b0e.png)

2022-06-02 22:10 UTC, tresorsawasawa commented on style.css
>  }
- [x] Kindly make sure to adjust the spacing at the top and bottom of all social media icons and the show-down buttons to make your project stick to the Figma design as much as possible. You can take a look at the previous images as they look different from the Figma design.

2022-06-02 22:10 UTC, tresorsawasawa commented on style.css
> +
- [ ] Kindly make sure you use all interactive colors on all the buttons of your project for the `hove`, `pressed`,... to make them match the Figma template. I suggest you check from this image below on Figma to pick the used colors.
![btns](https://user-images.githubusercontent.com/83042742/171742821-0bca90bb-18a7-4673-a2e3-a73a5e732760.png)

2022-06-02 22:10 UTC, tresorsawasawa commented on style.css
>  }
- [ ] I think it would be better to remove the `value=" email"` attribute in the email input and only use the placeholder text to make it looks better. 
- [ ] I also suggest doing the same on the `textarea` field. I would better use the `Enter text here` text as a placeholder instead of pitting in the tag.  This will make your form more professional
**Good**: `<textarea name="" id="" cols="30" rows="10" placeholder="Enter text here"></textarea>`
**Bad**:  `<textarea name="" id="" cols="30" rows="10">Enter text here</textarea>`

- [ ] Once you fix this issue make sure the add **padding** on **inputs text**: for `name filed`, `email field` and `message field`. I know you can do it :muscle: :muscle:

2022-06-02 22:10 UTC, tresorsawasawa commented on style.css
> +
- [x] Kindly make sure your footer sticks to the Figma template design. I suggest you fix the `spacing` at the top and bottom, `spacing` between social media icons, and the height of the footer to match the template as much as possible.

2022-06-02 22:10 UTC, tresorsawasawa commented on index.html
>    </header>
- [ ] Kindly make sure the header design matches the one from the Figma template. I suggest you check the **spacing** between and around the elements inside, the position of each element,... This will make your design now looks perfect :+1: :+1:
### Figma design:
![f_hd](https://user-images.githubusercontent.com/83042742/171746659-c663ff0c-084f-4c71-ba7e-00c1c7ccf056.png)

### Your design
![s_hd](https://user-images.githubusercontent.com/83042742/171746627-5ba66707-02d2-4f74-8cc8-fef1358fa00a.png)

2022-06-03 14:02 UTC, mukhammadrizooff requested changes
Hi @digia3d, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

<img src="https://media0.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

 ## Highlights
- Good implementation 💯 
- All linters passed 💯 
- Correct use of Gitflow 💯

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 14:02 UTC, mukhammadrizooff commented on index.html
> +      </div>
- [ ] [REQUIRED] Please make changes! It is not a good idea to use picture instead of word because you have got design mistake on right and left `work` elements. Please check again [FIGMA](https://www.figma.com/file/l7SqJ3ZfkAKih9sFxvWSR4/Microverse-Student-Project-1).

**Your Design**
![image](https://user-images.githubusercontent.com/63915024/171869006-489fdd28-539a-46d8-8a8a-aba2c3af0c36.png)
**Figma Design**
![image](https://user-images.githubusercontent.com/63915024/171869122-fdea6171-153f-4573-916d-3b7c1433bd2d.png)

2022-06-03 14:02 UTC, mukhammadrizooff commented on index.html
>          </label>
- [ ] [REQUIRED] Please make changes! The `name` and `last name` input text share the same row. But you miss adding `last name` input after the `name` input.

![image](https://user-images.githubusercontent.com/63915024/171866001-47de81eb-4470-428a-ace7-7ab368878734.png)

2022-06-03 14:02 UTC, mukhammadrizooff commented on index.html
> +
- [ ] [REQUUIRED] Please change the name of the `button`, it should be `Send` not `See Project`.

![image](https://user-images.githubusercontent.com/63915024/171866353-370c17a8-42ec-4f5a-ad51-bb59aaba6a13.png)

2022-06-03 14:12 UTC, digia3d commented on index.html
>          </label>
Hi, @mukhammadrizooff . This is what is mentioned in the requirements:
IMPORTANT NOTE some Figma design templates include two input fields (for first name and last name) in the desktop version and one input field (for full name) in the mobile version (look for those cases in Contact me or Get in touch sections). Please ignore this part of the design template and use only one input for the full name for all versions.

2022-06-03 17:49 UTC, vic778 commented on style.css
> +}
- [OPTIONAL ] Kindly make sure to add the correct spacing between languages items, Frameworks items, and Skills items to make the page clear and match the Figma template. Also, make sure to add the missing horizontal line at the top.

2022-06-03 17:49 UTC, vic778 commented on index.html
>    </header>
- [OPTIONAL]Kindly make sure the header design matches the one from the Figma template. I suggest you check the spacing between and around the elements inside, the position of each element,... This will make your design now looks perfect +1 +1

2022-06-03 17:52 UTC, vic778 requested changes
## Hello @digia3d 

Good job so far! I know you have worked hard on making this project.  There are some issues that you still need to work on to go to the next project but you are almost there!

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)
## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [x] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 19:10 UTC, vechicin requested changes
# Hi @digia3d  ✋, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🚨 


 ## Highlights ⚡ 

- [x] Good job implementing some of the previous reviewers' requirements. 

 ## Required Changes ♻️

- [ ] Your mobile design has been altered by your desktop design, particularly when it comes to background images. Kindly fix that as it is a project requirement.
- [ ] Don't forget to fix your merge conflicts as well!

<img width="358" alt="Screen Shot 2022-06-03 at 14 08 15" src="https://user-images.githubusercontent.com/82426682/171932280-68eb0957-c22d-489d-8561-b46ce0faffdb.png">

_Check the comments under the review._

## Optional suggestions 📂 

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-03 19:10 UTC, vechicin commented on index.html
>    <section class="headline">
You still need to implement the changes required by previous reviewers in this section. Kindly fix this.

2022-06-03 19:10 UTC, vechicin commented on index.html
> +          <button class="mail"><img src="img/Desktop/Union.png" alt=""></button>
I apologize if this wasn't mentioned by previous reviewers but your buttons are missing the `active` styling. Kindly implement it.

<img width="996" alt="Screen Shot 2022-06-03 at 13 53 14" src="https://user-images.githubusercontent.com/82426682/171929706-ab364252-5e3e-4bff-8076-5f28d1b1983d.png">

2022-06-03 19:10 UTC, vechicin commented on index.html
>    <section class="works">
Your `Works` section in the desktop version doesn't quite look like the one from the template design.

Here's your section:

<img width="721" alt="Screen Shot 2022-06-03 at 13 58 13" src="https://user-images.githubusercontent.com/82426682/171930609-e3655d60-4110-4950-b0d2-f96324ce8062.png">

Here's the template design section:

<img width="563" alt="Screen Shot 2022-06-03 at 13 58 52" src="https://user-images.githubusercontent.com/82426682/171930722-2fb682e0-362d-4e48-9b13-e55ecf10a8ce.png">

I could only take a screenshot of this portion, but I suggest you take a closer look at the template design because it looks quite different from your design.

2022-06-03 19:10 UTC, vechicin commented on index.html
> +          <input type="email" name="email" id="email" placeholder="  ujvari65@gmail.com" required>
[OPTIONAL] I recommend you change your placeholders. The reason why the template design has names and emails for these input placeholders is to showcase how the text is supposed to look when the user starts typing info, not because those are supposed to be the actual placeholders. I strongly suggest you implement this change because your placeholders give a weird look to the page and are not great from a UX standpoint.

2022-06-03 19:10 UTC, vechicin commented on index.html
>      <section class="footer">
Your `Footer` design doesn't quite match the template design.

Here's your footer:

<img width="1440" alt="Screen Shot 2022-06-03 at 14 05 14" src="https://user-images.githubusercontent.com/82426682/171931688-48d8e50a-2e25-460b-9847-5914e9673793.png">

Here's the template design footer:

<img width="565" alt="Screen Shot 2022-06-03 at 14 05 34" src="https://user-images.githubusercontent.com/82426682/171931745-f7575c71-2cff-4122-bf0a-d7cd2785afb5.png">

You should fix the margin with the section above as well as fix the spacing between the social media icons. Kindly do so.

2022-06-04 00:08 UTC, Kandy-Peter approved these changes
Hi @TekyRey,

# APPROVED 🟢 

![ObedientGreenAndeancat-max-1mb](https://user-images.githubusercontent.com/80612925/171843592-b0fc5921-ecaa-4f4d-820d-a43ba61ed023.gif)

Great implementation of all the requirements in this milestone. 👏
Your web app looks really fantastic. 🎉 

_You have done an amazing job 👍_

Your project is complete!  There is nothing else to say other than... it's time to merge it. :shipit: 

#### CONGRATULATIONS! 🎉 

##  Optional suggestion

- [ ] It would be better if you fix all conflicts you have in your current branch to be able to merge it. 

# CHEERS AND HAPPY CODING!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-06-04 00:08 UTC, Kandy-Peter commented on index.html
>      <section class="footer">
- [ ] OPTIONAL: Good job on making this change. I would also suggest you decrease the `padding-top` to match the more the Figma desing.

2022-06-04 00:08 UTC, Kandy-Peter commented on index.html
> +        <button type="submit" id="button-footer">Send</button>
- [ ] OPTIONAL: It would be nice to also implement optional suggestions to improve code and design quality. In this case implementing button actions like `active`, `hover`, and `disabled` is a good practice. Kindly add them.
![image](https://user-images.githubusercontent.com/80612925/171968402-2857766c-3577-45cb-80c4-a111bba76bea.png)

2022-06-04 07:07 UTC, merged